Repository cloud-barista/cb-mcks, pull requests merged in 2022-11, with the labels that each got.

#154 refactor: create a cluster api request structure
  docs/test/cluster-create.sh
  docs/test/node-add.sh
  src/core/app/ack.go
  src/core/app/const.go
  src/core/service/cluster.go
  src/core/service/node.go
  src/docs/docs.go
  src/docs/swagger.json
  src/docs/swagger.yaml
  src/grpc-api/server/mcar/cluster.go
  src/rest-api/router/cluster.go
  src/rest-api/router/node.go
Labels: documentation, refactoring

#156 feat:Add external etcd cluster
  docs/design/entity.md
  src/core/app/const.go
  src/core/model/types.go
  src/core/provision/machine.go
  src/core/provision/provisioner.go
  src/core/service/cluster.go
  src/core/service/mcir.go
  src/core/tumblebug/mcis.go
  src/core/tumblebug/types.go
  src/docs/docs.go
  src/docs/swagger.json
  src/docs/swagger.yaml
  src/rest-api/router/cluster.go
  src/scripts/bootstrap.sh
  src/scripts/etcd-ca.sh
  src/scripts/etcd-conf.sh
  src/scripts/k8s-init-etcd.sh
Labels: enhancement

#158 feat:Add support for NCP/NCPVPC
  docs/test/batch-register-cloud-info.sh.example
  docs/test/conf.env
  docs/test/connectioninfo-create.sh
  docs/test/env.sh
  src/core/app/const.go
  src/core/model/types.go
  src/core/provision/provisioner.go
  src/core/service/cluster.go
  src/core/service/csp.go
  src/core/service/mcir.go
  src/core/tumblebug/mcis.go
Labels: feature

#159 Update to lastest version spider/tumblebug
  src/core/provision/provisioner.go
  src/core/service/cluster.go
  src/core/service/mcir.go
  src/core/service/node.go
  src/core/tumblebug/mcis.go
  src/core/tumblebug/types.go
  src/rest-api/router/cluster.go
Labels: dependencies

#160 feat:Add support for NHN Cloud
  docs/test/batch-register-cloud-info.sh.example
  docs/test/connectioninfo-create.sh
  src/core/app/const.go
  src/core/model/types.go
  src/core/service/csp.go
  src/core/service/mcir.go
Labels: feature
