Repository cloud-barista/cb-mcks, pull requests merged in 2022-01, with the labels that each got.

#122 refactor: improve a structure
  Dockerfile
  README.md
  go.mod
  src/core/app/ack.go
  src/core/app/config.go
  src/core/app/const.go
  src/core/app/store.go
  src/core/common/common.go
  src/core/common/ns.go
  src/core/model/cluster.go
  src/core/model/node.go
  src/core/model/node_test.go
  src/core/model/request.go
  src/core/model/status.go
  src/core/model/tumblebug/base.go
  src/core/model/tumblebug/connection.go
  src/core/model/tumblebug/firewall.go
  src/core/model/tumblebug/image.go
  src/core/model/tumblebug/lookupimage.go
  src/core/model/tumblebug/lookupspec.go
  src/core/model/tumblebug/mcis.go
  src/core/model/tumblebug/ns.go
  src/core/model/tumblebug/region.go
  src/core/model/tumblebug/spec.go
  src/core/model/tumblebug/sshkey.go
  src/core/model/tumblebug/tvm.go
  src/core/model/tumblebug/vpc.go
  src/core/model/types.go
  src/core/model/vm.go
  src/core/provision/machine.go
  src/core/provision/provisioner.go
  src/core/provision/types.go
  src/core/service/cluster.go
  src/core/service/common.go
  src/core/service/csp.go
  src/core/service/mcir.go
  src/core/service/node.go
  src/core/tumblebug/base.go
  src/core/tumblebug/connection.go
  src/core/tumblebug/mcir.go
  src/core/tumblebug/mcis.go
  src/core/tumblebug/ns.go
  src/core/tumblebug/types.go
  src/docs/docs.go
  src/docs/swagger.json
  src/docs/swagger.yaml
  src/grpc-api/request/test/test_api.go
  src/grpc-api/server/mcar/cluster.go
  src/grpc-api/server/mcar/mcar.go
  src/grpc-api/server/mcar/node.go
  src/main.go
  src/rest-api/router/cluster.go
  src/rest-api/router/node.go
  src/rest-api/server.go
  src/utils/app/ack.go
  src/utils/app/client.go
  src/utils/config/config.go
  src/utils/config/const.go
  src/utils/lang/functions.go
Labels: refactoring

#124 fix: Duplicated private-ip problem on multiple VPCs
  src/core/model/types.go
  src/core/provision/machine.go
  src/core/provision/provisioner.go
  src/core/provision/types.go
  src/core/service/cluster.go
  src/core/service/csp.go
  src/core/service/mcir.go
  src/core/service/node.go
  src/core/tumblebug/mcir.go
  src/scripts/bootstrap.sh
Labels: bug, duplicate

#126 fix: Delete body for http get Method
  docs/test/connectioninfo-create.sh
  src/core/tumblebug/mcir.go
Labels: enhancement
